// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWN-KbxH8sKnmVKF12SjMRYtg2f2MKCH0',
    appId: '1:205798337458:web:260fe0ade8fabde9dad2ab',
    messagingSenderId: '205798337458',
    projectId: 'connectstopeople',
    authDomain: 'connectstopeople.firebaseapp.com',
    databaseURL: 'https://connectstopeople.firebaseio.com',
    storageBucket: 'connectstopeople.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCve-J5JNikb-ob4MEO15VeaCQ8be1HHe0',
    appId: '1:205798337458:android:e2d56aafe8ea9d36dad2ab',
    messagingSenderId: '205798337458',
    projectId: 'connectstopeople',
    databaseURL: 'https://connectstopeople.firebaseio.com',
    storageBucket: 'connectstopeople.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRi-cCSy5wcrdwOgmb3t2XxbLRfXG-vok',
    appId: '1:205798337458:ios:99487f8ca99ef7b2dad2ab',
    messagingSenderId: '205798337458',
    projectId: 'connectstopeople',
    databaseURL: 'https://connectstopeople.firebaseio.com',
    storageBucket: 'connectstopeople.appspot.com',
    iosClientId: '205798337458-ft8jcqp6sev0nnknjiv911dmui1d3fbo.apps.googleusercontent.com',
    iosBundleId: 'com.guruprasadhj.connect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRi-cCSy5wcrdwOgmb3t2XxbLRfXG-vok',
    appId: '1:205798337458:ios:99487f8ca99ef7b2dad2ab',
    messagingSenderId: '205798337458',
    projectId: 'connectstopeople',
    databaseURL: 'https://connectstopeople.firebaseio.com',
    storageBucket: 'connectstopeople.appspot.com',
    iosClientId: '205798337458-ft8jcqp6sev0nnknjiv911dmui1d3fbo.apps.googleusercontent.com',
    iosBundleId: 'com.guruprasadhj.connect',
  );
}
